[watcher]
# List of directories and files to ignore when watching for source file changes.
# Use 'ignore' key in the 'watcher' section.
ignore = [
    # Add specific patterns you need to ignore.
    "**/__pycache__/**",
    "*.py[co]",
    ".git",
    ".gitignore",
    ".env",
    "*.ini",
    "venv",
    ".venv",
    "**/venv/**",
    "**/.*",

    # *** Correct way to ignore torch and numpy in the watcher ***
    "torch",
    "**/torch/**",
    "numpy",
    "**/numpy/**",
]
